name: Bug Report
description: Report a bug or issue
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
        
  - type: input
    id: ha-version
    attributes:
      label: Home Assistant Version
      description: What version of Home Assistant are you running?
      placeholder: "2024.1.0"
    validations:
      required: true
      
  - type: input
    id: integration-version
    attributes:
      label: Integration Version
      description: What version of VOOL Modbus are you using?
      placeholder: "1.0.0"
    validations:
      required: true
      
  - type: dropdown
    id: device-type
    attributes:
      label: Device Type
      description: Which VOOL device are you using?
      options:
        - VOOL Charger
        - VOOL LMC
        - Both
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what the bug is
      placeholder: Tell us what you see!
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please copy and paste any relevant log output
      render: shell
